version: '3.4'

services:
  sql.data:
    hostname: sql_data
    image: microsoft/mssql-server-windows-developer

  orders.api:
    image: ${DOCKER_REGISTRY}ordersapi
    build:
      context: .
      dockerfile: Src\Services\Orders\Orders.API\Dockerfile
    depends_on:
      - sql.data

  catalog.api:
    image: ${DOCKER_REGISTRY}catalogapi
    build:
      context: .
      dockerfile: Src\Services\Catalog\Catalog.API\Dockerfile
    depends_on:
      - sql.data

